### ISSUE TITLE
fingerprint seems to change every time

### ISSUE THREAD

**Issue by konsumer** [actionhero/browser_fingerprint#90]
I am trying to use this lib in nextjs.

I do it server-side:

```js
const fingerPrinter = new BrowserFingerprint({
  cookieKey: "__browser_fingerprint",
  toSetCookie: true,
  onlyStaticElements: true,
  settings: {
    path: "/",
    expires: 3600000,
    httpOnly: null,
  },
})

export const getServerSideProps = async ({ req }) => {
  const { fingerprint } = fingerPrinter.fingerprint(req)
  return { props: { fingerprint } }
}
```

Then, in my component:

```js
export default ({ fingerprint }) => (
  <pre>{ fingerprint }</pre>
)
```

It changes every time.

`Chrome Version 89.0.4389.82 (Official Build) (x86_64)`

**Comment by evantahler** [comment]
Oh - I like this use-case!

I *think* that next.js' `getServerSideProps` is technically run on the server (yep) in an API route.  Can you confirm that the `req` object is actually the one from your browser, and not one from the frontend to to "backend" internal to next?  Perhaps via logging out headers or cookies?

**Comment by evantahler** [comment]
If you have a small test project, I'd be happy to take a look at it with you.

**Comment by konsumer** [comment]
I will set something up. Thanks!

**Comment by konsumer** [comment]
Ok, so [here is a minimal test](https://github.com/konsumer/fingerprint_test). Instructions in README.

You can run it locally or hit the [deployed version](https://fingerprint-test.vercel.app/).

Local should be plain nextjs direct link to server. I think the same is true for vercel, but I'm not sure.

**Comment by konsumer** [comment]
This seems not specific to vercel or next, as I made a very simple express app, with same problem:

```node
const express = require('express')
const { BrowserFingerprint } = require('browser_fingerprint')

const fingerPrinter = new BrowserFingerprint({
  cookieKey: '__browser_fingerprint',
  toSetCookie: true,
  onlyStaticElements: true,
  settings: {
    path: '/',
    expires: 3600000,
    httpOnly: null
  }
})

const app = express()

app.get('/', (req, res) => {
  const { fingerprint } = fingerPrinter.fingerprint(req)
  res.send(fingerprint)
})

console.log('test on http://localhost:8000')
app.listen(8000)
```

**Comment by konsumer** [comment]
I am on `Pop!_OS 20.10` which is basically a pre-configured Ubuntu 20.10.

**Comment by konsumer** [comment]
I also tested vercel+next (deployed and local) and express versions in Firefox 86.0 (64-bit) and had same issue.

**Comment by konsumer** [comment]
And here is a minimal cookie-test in express that works fine in Chrom/Firefox, without trying to read anything about user, other than cookie:

```js
const express = require('express')
const cookieParser = require('cookie-parser')
const crypto = require('crypto')

const app = express()

app.use(cookieParser())

app.get('/', (req, res) => {
  if (!req.cookies.id) {
    req.cookies.id = crypto.createHash('md5').update(Date.now() + '').digest('hex')
    res.cookie('id', req.cookies.id)
  }
  res.send(req.cookies.id)
})

console.log('test on http://localhost:8000')
app.listen(8000)
```

Since I'm really looking for unique visitors across multiple page--loads of same app, I might end up going with this.

**Comment by konsumer** [comment]
Here is an example of similar that works, in nextjs:

```js
import React from 'react'
import Cookies from 'cookies'
import crypto from 'crypto'

export const getServerSideProps = async ({ req, res }) => {
  const cookies = new Cookies(req, res)
  let fingerprint = cookies.get('id')
  if (!fingerprint) {
    fingerprint = crypto.createHash('md5').update(Date.now() + '').digest('hex')
    cookies.set('id', fingerprint)
  }
  return {
    props: { fingerprint }
  }
}

export default ({ fingerprint }) => (
  <pre>{fingerprint}</pre>
)
```

**Comment by konsumer** [comment]
So, my guess is that some header is being hashed, that both Firefox & Chrome are setting, that changes between loads.

**Comment by evantahler** [comment]
Thanks for all the examples!

I think the main misunderstanding is that browserFingerprint sets the headers to write the cookie itself.  It doesn't!   In the readme, you still need to `res.writeHead(200, headersHash)` where `headersHash` is generated by browseFingerprint.  The option `toSetCookie` will generate the header... but not apply it to the response object... which is probably confusing.

Now next doesn't want you ending the connection yourself, so you can use the `Cookies` library to help you out here, and set the fingerprint gives you.  I've got it working on my branch here I think - https://github.com/evantahler/fingerprint_test

**Comment by konsumer** [comment]
Makes sense. Thanks!

**Comment by konsumer** [comment]
I just looked at source, and see that `onlyStaticElements` should make it work this way, so it seems like a bug to me.

**Comment by evantahler** [comment]
Closing due to lack of response
